flora = {}

local path = minetest.get_modpath("flora")
dofile(path.."/functions.lua")
dofile(path.."/bush.lua")
dofile(path.."/coral.lua")
dofile(path.."/flower.lua")
dofile(path.."/plant.lua")
dofile(path.."/tree.lua")
dofile(path.."/flower.lua")
dofile(path.."/sfcave.lua")
dofile(path.."/underground.lua")
dofile(path.."/shapes.lua")
dofile(path.."/schem_alias.lua")
dofile(path.."/mushrooms.lua")