
-- blocks / brick.lua
minetest.register_alias("default:clay_brick", "blocks:clay_brick")
minetest.register_alias("default:clay_lump", "blocks:clay_lump")
minetest.register_alias("default:clay", "blocks:clay")
minetest.register_alias("default:brick", "blocks:stone")


-- blocks / book.lua
minetest.register_alias("default:paper", "blocks:paper")
minetest.register_alias("default:book", "blocks:book")
minetest.register_alias("default:book_written", "blocks:book_written")
minetest.register_alias("default:bookshelf", "blocks:bookshelf")

-- blocks / ladder.lua
minetest.register_alias("default:ladder_wood", "blocks:ladder_wood")
minetest.register_alias("default:ladder_steel", "blocks:ladder_steel")

-- blocks / sign.lua
minetest.register_alias("default:sign_wall_wood", "blocks:sign_wood")
minetest.register_alias("default:sign_wall_steel", "blocks:sign_steel")

-- blocks / cloud.lua
minetest.register_alias("default:cloud", "blocks:cloud")

-- blocks / liquid.lua
minetest.register_alias("default:water_source", "blocks:water_source")
minetest.register_alias("default:water_flowing", "blocks:water_flowing")
minetest.register_alias("default:river_water_source", "blocks:river_water_source")
minetest.register_alias("default:river_water_flowing", "blocks:river_water_flowing")
minetest.register_alias("default:lava_source", "blocks:lava_source")
minetest.register_alias("default:lava_flowing", "blocks:lava_flowing")

-- blocks / glass.lua
minetest.register_alias("default:glass", "blocks:glass")
minetest.register_alias("default:obsidian_glass", "blocks:obsidian_glass")

-- blocks / ore.lua
minetest.register_alias("default:coal_lump", "blocks:coal_lump")
minetest.register_alias("default:stone_with_coal", "blocks:stone_with_coal")
minetest.register_alias("default:coalblock", "blocks:coalblock")
minetest.register_alias("default:iron_lump", "blocks:iron_lump")
minetest.register_alias("default:stone_with_iron", "blocks:stone_with_iron")
minetest.register_alias("default:steel_ingot", "blocks:steel_ingot")
minetest.register_alias("default:steelblock", "blocks:steelblock")
minetest.register_alias("default:copper_ingot", "blocks:copper_ingot")
minetest.register_alias("default:copper_lump", "blocks:copper_lump")
minetest.register_alias("default:stone_with_copper", "blocks:stone_with_copper")
minetest.register_alias("default:copperblock", "blocks:copperblock")
minetest.register_alias("default:tin_ingot", "blocks:tin_ingot")
minetest.register_alias("default:tin_lump", "blocks:tin_lump")
minetest.register_alias("default:stone_with_tin", "blocks:stone_with_tin")
minetest.register_alias("default:tinblock", "blocks:tinblock")
minetest.register_alias("default:bronze_ingot", "blocks:bronze_ingot")
minetest.register_alias("default:bronzeblock", "blocks:bronzeblock")
minetest.register_alias("default:mese_crystal", "blocks:mese_crystal")
minetest.register_alias("default:mese_crystal_fragment", "blocks:mese_crystal_fragment")
minetest.register_alias("default:stone_with_mese", "blocks:stone_with_mese")
minetest.register_alias("default:mese", "blocks:mese")
minetest.register_alias("default:gold_ingot", "blocks:gold_ingot")
minetest.register_alias("default:gold_lump", "blocks:gold_lump")
minetest.register_alias("default:stone_with_gold", "blocks:stone_with_gold")
minetest.register_alias("default:goldblock", "blocks:goldblock")
minetest.register_alias("default:diamond", "blocks:diamond")
minetest.register_alias("default:stone_with_diamond", "blocks:stone_with_diamond")
minetest.register_alias("default:diamondblock", "blocks:diamondblock")

-- blocks / dirt.lua
minetest.register_alias("default:dirt", "blocks:dirt")
minetest.register_alias("default:dirt_with_grass", "blocks:dirt_with_grass")
minetest.register_alias("default:dirt_with_grass_footsteps", "blocks:dirt_with_grass_footsteps")
minetest.register_alias("default:dirt_with_dry_grass", "blocks:dirt_with_dry_grass")
minetest.register_alias("default:dirt_with_snow", "blocks:dirt_with_snow")
minetest.register_alias("default:dirt_with_rainforest_litter", "blocks:dirt_with_rainforest_litter")
minetest.register_alias("default:dirt_with_coniferous_litter", "blocks:dirt_with_coniferous_litter")
minetest.register_alias("default:dry_dirt", "blocks:dry_dirt")
minetest.register_alias("default:dry_dirt_with_dry_grass", "blocks:dry_dirt_with_dry_grass")

-- blocks / sand.lua
minetest.register_alias("default:sand", "blocks:sand")
minetest.register_alias("default:desert_sand", "blocks:desert_sand")
minetest.register_alias("default:silver_sand", "blocks:silver_sand")
minetest.register_alias("default:flint", "blocks:flint")
minetest.register_alias("default:gravel", "blocks:gravel")

-- blocks / snow.lua
minetest.register_alias("default:permafrost", "blocks:permafrost")
minetest.register_alias("default:permafrost_with_stones", "blocks:permafrost_with_stones")
minetest.register_alias("default:permafrost_with_moss", "blocks:permafrost_with_moss")
minetest.register_alias("default:snow", "blocks:snow")
minetest.register_alias("default:snowblock", "blocks:snowblock")
minetest.register_alias("default:ice", "blocks:ice")
minetest.register_alias("default:cave_ice", "blocks:cave_ice")

-- blocks / plank.lua
minetest.register_alias("default:stick", "blocks:stick")
minetest.register_alias("default:wood", "blocks:wood")
minetest.register_alias("default:junglewood", "blocks:junglewood")
minetest.register_alias("default:pine_wood", "blocks:pine_wood")
minetest.register_alias("default:acacia_wood", "blocks:acacia_wood")
minetest.register_alias("default:aspen_wood", "blocks:aspen_wood")

-- blocks / stone.lua
minetest.register_alias("default:stone", "blocks:stone")
minetest.register_alias("default:cobble", "blocks:cobble")
minetest.register_alias("default:stonebrick", "blocks:stonebrick")
minetest.register_alias("default:stone_block", "blocks:stone_block")
minetest.register_alias("default:mossycobble", "blocks:mossycobble")
minetest.register_alias("default:desert_stone", "blocks:desert_stone")
minetest.register_alias("default:desert_cobble", "blocks:desert_cobble")
minetest.register_alias("default:desert_stonebrick", "blocks:desert_stonebrick")
minetest.register_alias("default:desert_stone_block", "blocks:desert_stone_block")
minetest.register_alias("default:sandstone", "blocks:sandstone")
minetest.register_alias("default:sandstonebrick", "blocks:sandstonebrick")
minetest.register_alias("default:sandstone_block", "blocks:sandstone_block")
minetest.register_alias("default:desert_sandstone", "blocks:desert_sandstone")
minetest.register_alias("default:desert_sandstone_brick", "blocks:desert_sandstone_brick")
minetest.register_alias("default:desert_sandstone_block", "blocks:desert_sandstone_block")
minetest.register_alias("default:silver_sandstone", "blocks:silver_sandstone")
minetest.register_alias("default:silver_sandstone_brick", "blocks:silver_sandstone_brick")
minetest.register_alias("default:silver_sandstone_block", "blocks:silver_sandstone_block")
minetest.register_alias("default:obsidian_shard", "blocks:obsidian_shard")
minetest.register_alias("default:obsidian", "blocks:obsidian")
minetest.register_alias("default:obsidianbrick", "blocks:obsidianbrick")
minetest.register_alias("default:obsidian_block", "blocks:obsidian_block")

-- blocks / torch.lua
minetest.register_alias("default:furnace", "blocks:furnace")

-- blocks / chest.lua
minetest.register_alias("default:chest_locked", "blocks:chest_locked")
minetest.register_alias("default:chest", "blocks:chest")

-- blocks / furnace.lua
minetest.register_alias("default:furnace", "blocks:furnace")

-- flora / coral.lua
minetest.register_alias("default:sand_with_kelp", "flora:sand_with_kelp")
minetest.register_alias("default:coral_green", "flora:coral_green")
minetest.register_alias("default:coral_pink", "flora:coral_pink")
minetest.register_alias("default:coral_cyan", "flora:coral_cyan")
minetest.register_alias("default:coral_brown", "flora:coral_brown")
minetest.register_alias("default:coral_orange", "flora:coral_orange")
minetest.register_alias("default:coral_skeleton", "flora:coral_skeleton")

-- tools / key.lua
minetest.register_alias("default:key", "tools:key")
minetest.register_alias("default:skeleton_key", "tools:skeleton_key")

-- tools / basic.lua
minetest.register_alias("default:pick_wood", "tools:pick_wood")
minetest.register_alias("default:pick_stone", "tools:pick_stone")
minetest.register_alias("default:pick_bronze", "tools:pick_bronze")
minetest.register_alias("default:pick_steel", "tools:pick_steel")
minetest.register_alias("default:pick_mese", "tools:pick_mese")
minetest.register_alias("default:pick_diamond", "tools:pick_diamond")
minetest.register_alias("default:shovel_wood", "tools:shovel_wood")
minetest.register_alias("default:shovel_stone", "tools:shovel_stone")
minetest.register_alias("default:shovel_bronze", "tools:shovel_bronze")
minetest.register_alias("default:shovel_steel", "tools:shovel_steel")
minetest.register_alias("default:shovel_mese", "tools:shovel_mese")
minetest.register_alias("default:shovel_diamond", "tools:shovel_diamond")
minetest.register_alias("default:axe_wood", "tools:axe_wood")
minetest.register_alias("default:axe_stone", "tools:axe_stone")
minetest.register_alias("default:axe_bronze", "tools:axe_bronze")
minetest.register_alias("default:axe_steel", "tools:axe_steel")
minetest.register_alias("default:axe_mese", "tools:axe_mese")
minetest.register_alias("default:axe_diamond", "tools:axe_diamond")
minetest.register_alias("default:sword_wood", "tools:sword_wood")
minetest.register_alias("default:sword_stone", "tools:sword_stone")
minetest.register_alias("default:sword_bronze", "tools:sword_bronze")
minetest.register_alias("default:sword_steel", "tools:sword_steel")
minetest.register_alias("default:sword_mese", "tools:sword_mese")
minetest.register_alias("default:sword_diamond", "tools:sword_diamond")

-- flora / plant.lua
minetest.register_alias("default:cactus", "flora:cactus")
minetest.register_alias("default:large_cactus_seedling", "flora:large_cactus_seedling")
minetest.register_alias("default:papyrus", "flora:papyrus")
minetest.register_alias("default:dry_shrub", "flora:dry_shrub")
minetest.register_alias("default:junglegrass", "flora:junglegrass")
minetest.register_alias("default:grass_1", "flora:grass_1")
minetest.register_alias("default:grass_2", "flora:grass_2")
minetest.register_alias("default:grass_3", "flora:grass_3")
minetest.register_alias("default:grass_4", "flora:grass_4")
minetest.register_alias("default:grass_5", "flora:grass_5")
minetest.register_alias("default:dry_grass_1", "flora:dry_grass_1")
minetest.register_alias("default:dry_grass_2", "flora:dry_grass_2")
minetest.register_alias("default:dry_grass_3", "flora:dry_grass_3")
minetest.register_alias("default:dry_grass_4", "flora:dry_grass_4")
minetest.register_alias("default:dry_grass_5", "flora:dry_grass_5")
minetest.register_alias("default:fern_1", "flora:fern_1")
minetest.register_alias("default:fern_2", "flora:fern_2")
minetest.register_alias("default:fern_3", "flora:fern_3")
minetest.register_alias("default:marram_grass_1", "flora:marram_grass_1")
minetest.register_alias("default:marram_grass_2", "flora:marram_grass_2")
minetest.register_alias("default:marram_grass_3", "flora:marram_grass_3")

-- flora / coral.lua
minetest.register_alias("default:sand_with_kelp", "flora:sand_with_kelp")
minetest.register_alias("default:coral_green", "flora:coral_green")
minetest.register_alias("default:coral_pink", "flora:coral_pink")
minetest.register_alias("default:coral_cyan", "flora:coral_cyan")
minetest.register_alias("default:coral_brown", "flora:coral_brown")
minetest.register_alias("default:coral_orange", "flora:coral_orange")
minetest.register_alias("default:coral_skeleton", "flora:coral_skeleton")

-- flora / bush.lua
minetest.register_alias("default:bush_stem", "flora:bush_stem")
minetest.register_alias("default:bush_leaves", "flora:bush_leaves")
minetest.register_alias("default:bush_sapling", "flora:bush_sapling")
minetest.register_alias("default:blueberries", "flora:blueberries")
minetest.register_alias("default:blueberry_bush_leaves_with_berries", "flora:blueberry_bush_leaves_with_berries")
minetest.register_alias("default:blueberry_bush_leaves", "flora:blueberry_bush_leaves")
minetest.register_alias("default:blueberry_bush_sapling", "flora:blueberry_bush_sapling")
minetest.register_alias("default:acacia_bush_stem", "flora:acacia_bush_stem")
minetest.register_alias("default:acacia_bush_leaves", "flora:acacia_bush_leaves")
minetest.register_alias("default:acacia_bush_sapling", "flora:acacia_bush_sapling")
minetest.register_alias("default:pine_bush_stem", "flora:pine_bush_stem")
minetest.register_alias("default:pine_bush_needles", "flora:pine_bush_needles")
minetest.register_alias("default:pine_bush_sapling", "flora:pine_bush_sapling")

-- flora / tree.lua
minetest.register_alias("default:tree", "flora:tree")
minetest.register_alias("default:sapling", "flora:sapling")
minetest.register_alias("default:leaves", "flora:leaves")
minetest.register_alias("default:apple", "flora:apple")
minetest.register_alias("default:apple_mark", "flora:apple_mark")
minetest.register_alias("default:jungletree", "flora:jungletree")
minetest.register_alias("default:jungleleaves", "flora:jungleleaves")
minetest.register_alias("default:junglesapling", "flora:junglesapling")
minetest.register_alias("default:emergent_jungle_sapling", "flora:emergent_jungle_sapling")
minetest.register_alias("default:pine_tree", "flora:pine_tree")
minetest.register_alias("default:pine_needles", "flora:pine_needles")
minetest.register_alias("default:pine_sapling", "flora:pine_sapling")
minetest.register_alias("default:acacia_tree", "flora:acacia_tree")
minetest.register_alias("default:acacia_leaves", "flora:acacia_leaves")
minetest.register_alias("default:acacia_sapling", "flora:acacia_sapling")
minetest.register_alias("default:aspen_tree", "flora:aspen_tree")
minetest.register_alias("default:aspen_leaves", "flora:aspen_leaves")
minetest.register_alias("default:aspen_sapling", "flora:aspen_sapling")

-- blocks / wool.lua
minetest.register_alias("wool:red", "blocks:wool_red")
minetest.register_alias("wool:blue", "blocks:wool_blue")
minetest.register_alias("wool:cyan", "blocks:wool_cyan")
minetest.register_alias("wool:grey", "blocks:wool_grey")
minetest.register_alias("wool:pink", "blocks:wool_pink")
minetest.register_alias("wool:black", "blocks:wool_black")
minetest.register_alias("wool:brown", "blocks:wool_brown")
minetest.register_alias("wool:green", "blocks:wool_green")
minetest.register_alias("wool:white", "blocks:wool_white")
minetest.register_alias("wool:orange", "blocks:wool_orange")
minetest.register_alias("wool:violet", "blocks:wool_violet")
minetest.register_alias("wool:yellow", "blocks:wool_yellow")
minetest.register_alias("wool:magenta", "blocks:wool_magenta")
minetest.register_alias("wool:dark_grey", "blocks:wool_dark_grey")
minetest.register_alias("wool:dark_green", "blocks:wool_dark_green")

-- tools / screwdriver.lua
minetest.register_alias("screwdriver:screwdriver", "tools:screwdriver")

-- flora / flower.lua
minetest.register_alias("flowers:rose", "flora:rose")
minetest.register_alias("flowers:flowers", "flora:flowers")
minetest.register_alias("flowers:dandelion_yellow", "flora:dandelion_yellow")
minetest.register_alias("flowers:geranium", "flora:geranium")
minetest.register_alias("flowers:viola", "flora:viola")
minetest.register_alias("flowers:dandelion_white", "flora:dandelion_white")
minetest.register_alias("flowers:mushroom_brown", "flora:mushroom_brown")
minetest.register_alias("flowers:mushroom_red", "flora:mushroom_red")
minetest.register_alias("flowers:waterlily", "flora:waterlily")
minetest.register_alias("flowers:waterlily_waving", "flora:waterlily_waving")

-- blocks / vessels.lua
minetest.register_alias("vessels:shelf", "blocks:vesselshelf")
minetest.register_alias("vessels:glass_bottle", "blocks:glass_bottle")
minetest.register_alias("vessels:drinking_glass", "blocks:drinking_glass")
minetest.register_alias("vessels:steel_bottle", "blocks:steel_bottle")
minetest.register_alias("vessels:glass_fragments", "blocks:glass_fragments")