blocks = {}

local path = minetest.get_modpath("blocks")
dofile(path.."/book.lua")
dofile(path.."/brick.lua")
dofile(path.."/chest.lua")
dofile(path.."/dirt.lua")
dofile(path.."/furnace.lua")
dofile(path.."/glass.lua")
dofile(path.."/ladder.lua")
dofile(path.."/liquid.lua")
dofile(path.."/misc.lua")
dofile(path.."/ore.lua")
dofile(path.."/plank.lua")
dofile(path.."/sign.lua")
dofile(path.."/stone.lua")
dofile(path.."/torch.lua")
dofile(path.."/lamp.lua")
dofile(path.."/wool.lua")
dofile(path.."/vessel.lua")
dofile(path.."/sand.lua")
dofile(path.."/snow.lua")
dofile(path.."/shapes.lua")