blocks = {}

local default_path = minetest.get_modpath("blocks")
dofile(default_path .. "/book.lua")
dofile(default_path .. "/brick.lua")
dofile(default_path .. "/chest.lua")
dofile(default_path .. "/dirt.lua")
dofile(default_path .. "/furnace.lua")
dofile(default_path .. "/glass.lua")
dofile(default_path .. "/ladder.lua")
dofile(default_path .. "/liquid.lua")
dofile(default_path .. "/misc.lua")
dofile(default_path .. "/ore.lua")
dofile(default_path .. "/plank.lua")
dofile(default_path .. "/sign.lua")
dofile(default_path .. "/stone.lua")
dofile(default_path .. "/torch.lua")
dofile(default_path .. "/lamp.lua")
dofile(default_path .. "/wool.lua")
dofile(default_path .. "/vessel.lua")
dofile(default_path .. "/sand.lua")
dofile(default_path .. "/snow.lua")
